name: Demo GitHub Actions
on:
  push:
    branches:
      - main
run-name: ${{ github.actor }} is running ${{ github.workflow }} on ${{ github.repository }}
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Version of workflow 1.0"
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: clean up
        run: rm -rf package-lock.json .npmrc
      - name: Install dependencies
        run: npm i
      - name: Run a test
        run: npm test
      - name: Run SonarScanner
        uses: addnab/docker-run-action@v3
        with:
          image: sonarsource/sonar-scanner-cli
          options: -v ${{ github.workspace }}:/usr/src -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN_TEST }} -e SONAR_HOST_URL=${{ SONAR_URL }}